### ISSUE TITLE
cakephp-dompdf header and footer are not in the proper positions, but rather at the beginning of page

### ISSUE THREAD

**Issue by mbojanks** [DaoAndCo/cakephp-dompdf#1]
When I installed cakephp-dompdf from composer as you recommended, Test example does not show header and footer in their proper positions, but rather at the beginning of page. On another computer's xampp instalation, everything is just fine. Please suggest what could disturb the proper operation.

Thank you. Kindest regards,
Bojan

**Comment by ozee31** [comment]
Have you run the command `bin/cake plugin assets symlink` ?
[http://book.cakephp.org/3.0/en/deployment.html#symlink-assets](documentation)

If you have a problem with the header and Footer, the most likely explanation was the css file is not loaded correctly

**Comment by mbojanks** [comment]
Thank you. Yes, but it was not effective, I suppose. When I deleted and created symlinks again, everything was ok. Closing the issue, then...
