### ISSUE TITLE
PDF not generating without table border and 5 rows 

### ISSUE THREAD

**Issue by viveksudalai** [DaoAndCo/cakephp-dompdf#7]
I am trying to create pdf. I have three column table with border "1" in the CTP file. PDF is not generating when the table have only few rows.  PDF is generated after adding some extra rows with empty TD. 
 One more problem is if I change table border to 0 then it's stop generating PDF.

I don't want the border for empty rows. so tried to change the TD border colour to white.then applied 
Style border colour white to all 3 empty TD to make it as invisible in the pdf. 
If I applied style to all 3 column then again it is stop generating PDF. But it is working when I applied only to first column.

Please help on this issue

**Comment by ozee31** [comment]
Hi, it's a problem with DomPdf lib, this lib is just a helper. Send an issue [here](https://github.com/dompdf/dompdf/issues)
